### ISSUE TITLE
README - can you explain the project in more detail? Is it Chrome and Firefox both? How do you install it:?

### ISSUE THREAD

**Issue by RocketDerp** [duncanlang/Wikidata-Checker#1]
Thank you.

**Comment by RocketDerp** [comment]
Ok, I checked it out with git and turned on Developer Mode in Chrome on Windows 11. I added the unpacked extension. However, when I visit a Letterboxd page like: https://letterboxd.com/film/the-red-badge-of-courage-1974/


I get an uncaught exception on line 228:
     				return this.stopRunning();

**Comment by duncanlang** [comment]
It's not exactly clear what is causing your error. I have added a release with the signed .xpi for Firefox, try the addon this way and see if it works correctly.

**Comment by RocketDerp** [comment]
Thanks for updating the README. Ok, so I downloaded the extension on Firefox and installed it. But when I visit LetterboxD I'm not seeing anything: https://letterboxd.com/film/the-red-badge-of-courage-1974/ - which has an entry on WikiData: https://www.wikidata.org/wiki/Q4063266

Looking in the Firefox developer console, I do see messages about the requests being made:

``
Wikidata-Checker | Calling: https://query.wikidata.org/bigdata/namespace/wdq/sparql?format=json&query=SELECT DISTINCT ?item ?itemLabel ?Rotten_Tomatoes_ID ?Metacritic_ID ?Letterboxd_ID ?Wikipedia ?InstanceLabel ?Anidb_ID ?Anilist_ID ?MAL_ID ?MPAA_film_ratingLabel ?Budget ?Budget_UnitLabel ?Box_OfficeUS ?Box_OfficeUS_UnitLabel ?Box_OfficeWW ?Box_OfficeWW_UnitLabel ?Publication_Date ?Publication_Date_Precision ?Publication_Date_Backup ?Publication_Date_Backup_Precision ?Publication_Date_Origin ?Publication_Date_Origin_Precision ?US_Title ?TV_Start ?TV_Start_Precision ?TV_End ?TV_End_Precision WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  {
    SELECT DISTINCT ?item WHERE {
      ?item p:P345 ?statement0.
      ?statement0 ps:P345 "tt0072069".
    }
    LIMIT 10
  }
  OPTIONAL { ?item wdt:P1258 ?Rotten_Tomatoes_ID. }
  OPTIONAL { ?item wdt:P1712 ?Metacritic_ID. }
  OPTIONAL { ?item wdt:P6127 ?Letterboxd_ID. }
  OPTIONAL { ?item wdt:P5646 ?Anidb_ID. }
  OPTIONAL { ?item wdt:P8729 ?Anilist_ID. }
  OPTIONAL { ?item wdt:P4086 ?MAL_ID. }
  OPTIONAL { ?item wdt:P1657 ?MPAA_film_rating. } 
  OPTIONAL {
    ?Wikipedia schema:about ?item .
    ?Wikipedia schema:inLanguage "en" .
    ?Wikipedia schema:isPartOf <https://en.wikipedia.org/> .
  }
  OPTIONAL { ?item wdt:P31 ?Instance. } 
  OPTIONAL {
    ?item p:P2130 ?Budget_Entry.
    ?Budget_Entry ps:P2130 ?Budget.
    OPTIONAL {
      ?Budget_Entry psv:P2130 ?valuenode.
      ?valuenode wikibase:quantityUnit ?Budget_Unit.
      ?Budget_Unit p:P498 [ps:P498 ?Budget_UnitLabel].
    }
    MINUS { ?Budget_Entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item p:P2142 ?Box_Office_Entry.
    ?Box_Office_Entry ps:P2142 ?Box_OfficeUS;
      pq:P3005 wd:Q30.
    OPTIONAL {
      ?Box_Office_Entry psv:P2142 ?valuenode2.
      ?valuenode2 wikibase:quantityUnit ?Box_Office_Unit.
      ?Box_Office_Unit p:P498 [ps:P498 ?Box_OfficeUS_UnitLabel].
    }
    MINUS { ?Box_Office_Entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item p:P2142 ?Box_Office_Entry.
    ?Box_Office_Entry ps:P2142 ?Box_OfficeUS;
      pq:P3005 wd:Q2017699.
    OPTIONAL {
      ?Box_Office_Entry psv:P2142 ?valuenode2.
      ?valuenode2 wikibase:quantityUnit ?Box_Office_Unit.
      ?Box_Office_Unit p:P498 [ps:P498 ?Box_OfficeUS_UnitLabel].
    }
    MINUS { ?Box_Office_Entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item p:P2142 ?Box_Office_EntryWW.
    ?Box_Office_EntryWW ps:P2142 ?Box_OfficeWW;
      pq:P3005 wd:Q13780930.
    OPTIONAL {
      ?Box_Office_EntryWW psv:P2142 ?valuenode3.
      ?valuenode3 wikibase:quantityUnit ?Box_OfficeWW_Unit.
      ?Box_OfficeWW_Unit p:P498 [ps:P498 ?Box_OfficeWW_UnitLabel].
    }
    MINUS { ?Box_Office_EntryWW wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item p:P577 ?Publication_Date_entry.
    ?Publication_Date_entry ps:P577 ?Publication_Date;
      pq:P291 wd:Q30.
    ?Publication_Date_entry psv:P577 [wikibase:timePrecision ?Publication_Date_Precision].
    MINUS { ?Publication_Date_entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item p:P577 ?Publication_Date_Backup_entry.
    ?Publication_Date_Backup_entry ps:P577 ?Publication_Date_Backup.
    ?Publication_Date_Backup_entry psv:P577 [wikibase:timePrecision ?Publication_Date_Backup_Precision].
    FILTER NOT EXISTS { ?Publication_Date_Backup_entry pq:P291 [] }
    MINUS { ?Publication_Date_Backup_entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL {
    ?item wdt:P495 ?Country_Of_Origin.
    OPTIONAL {
      ?item p:P577 ?Date_Origin_entry.
      ?Date_Origin_entry ps:P577 ?Publication_Date_Origin;
        pq:P291 ?Country_Of_Origin.
      ?Date_Origin_entry psv:P577 [wikibase:timePrecision ?Publication_Date_Origin_Precision].
      MINUS { ?Date_Origin_entry wikibase:rank wikibase:DeprecatedRank. }
    }
  }
  OPTIONAL {
    ?item p:P1476 ?Title_Entry.
    ?Title_Entry ps:P1476 ?US_Title;
      pq:P3005 wd:Q30.
  }
  OPTIONAL { 
    ?item p:P580 ?TV_Start_entry.
    ?TV_Start_entry ps:P580 ?TV_Start.
    ?TV_Start_entry psv:P580 [wikibase:timePrecision ?TV_Start_Precision].
    MINUS { ?TV_Start_entry wikibase:rank wikibase:DeprecatedRank. }
  }
  OPTIONAL { 
    ?item p:P582 ?TV_End_entry.
    ?TV_End_entry ps:P582 ?TV_End.
    ?TV_End_entry psv:P582 [wikibase:timePrecision ?TV_End_Precision].
    MINUS { ?TV_End_entry wikibase:rank wikibase:DeprecatedRank. }
  }
} wikidata-checker.user.js:582:13
Wikidata-Checker | Calling: https://www.imdb.com/title/tt0072069 wikidata-checker.user.js:567:13
WikiData-Checker | Calling: https://www.omdbapi.com/?apikey=afd82b43&i=tt0072069&plot=short&r=json&tomatoes=true wikidata-checker.user.js:201:15

**Comment by duncanlang** [comment]
I never wrote or tested it to work on Chrome as I use Firefox
